[application]

# App (Project) Name
name = "Heritage Wallet"

[web.app]

# HTML title tag content
title = "Heritage Wallet"

# include `assets` in web platform
[web.resource]

# CSS style file
style = []

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
